# Generated by Django 4.1.6 on 2023-04-01 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
