# Generated by Django 4.1.6 on 2023-04-13 11:36

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('body', ckeditor.fields.RichTextField()),
                ('picture', models.CharField(blank=True, max_length=600, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True)),
                ('noindex', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=300, null=True)),
                ('is_sub', models.BooleanField(default=False)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub', to='blog.category')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('body', ckeditor.fields.RichTextField()),
                ('picture', models.CharField(blank=True, max_length=600, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True)),
                ('noindex', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('body', ckeditor.fields.RichTextField()),
                ('picture', models.CharField(blank=True, max_length=600, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=200, null=True)),
                ('meta_description', models.CharField(blank=True, max_length=200, null=True)),
                ('noindex', models.BooleanField(default=False)),
                ('canonical', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('situation', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending Review', 'Pending')], default='Draft', max_length=14)),
                ('category', models.ManyToManyField(related_name='posts', to='blog.category')),
                ('tag', models.ManyToManyField(related_name='posts', to='blog.tag')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
