# Generated by Django 4.1.6 on 2023-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_options_comment_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='situation',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending Review', 'Pending')], default='Draft', max_length=14),
        ),
    ]
